# Go cross compiler (xgo): Wildcard layer to the latest 1.8 release
# Copyright (c) 2017 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM ykyuen/xgo-1.8.4

MAINTAINER Péter Szilágyi <peterke@gmail.com>
